### ISSUE TITLE
Order of config.rb activated after_build callbacks is not preserved.

### ISSUE THREAD

**Issue by ewlarson** [plasticine/middleman-imageoptim#10]
Because the extension's after_build optimize task is wrapped inside of the after_configuration block, the order of config.rb after_build callbacks is not respected.  See this thread from the MM forum for details:
http://forum.middlemanapp.com/t/order-of-after-build-callbacks/901/8

Because nothing occurs in this extensions after_configuration block that isn't specified in the nested after_build callback, it's an easy fix to remedy this issue: just remove the unnecessary after_configuration block surrounding the after_build code.  I'll submit a pull request with the change now.

**Comment by plasticine** [comment]
Should be fixed by #29
