### ISSUE TITLE
Understanding logs during build

### ISSUE THREAD

**Issue by thenoelforte** [plasticine/middleman-imageoptim#21]
Hi,

I'm just trying to understand if this is normal behavior...during build, the terminal occasionally throws up a few lines similar to this between images:

    sh: line 1: 27776 Trace/BPT trap: 5       env PATH=:/Users/nforte/.rvm/gems/ruby-2.1.2/bin:/Users/nforte/.rvm/gems/ruby-2.1.2@global/bin:/Users/nforte/.rvm/rubies/ruby-2.1.2/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/bin:/Users/nforte/.rvm/bin:/Users/nforte/.rvm/gems/ruby-2.1.2/gems/image_optim-0.9.1/vendor nice -n 10 jpegoptim --strip-all -q -- /var/folders/jj/k9hbxrq16b58_6f8n7bschjw0000gn/T/intro20140711-24912-1i91krw.jpg > /dev/null 2>&1

If some could clarify is this is problem or not, and if so, how to fix it.

**Comment by plasticine** [comment]
Suspect that this is actually an `image_optim` worker doing something funny under the hood.

**Comment by plasticine** [comment]
I’m about to push out `0.2.0`, which has a vastly updated version of `image_optim`—please try that version and see if it resolves your issue.
