### ISSUE TITLE
alternatively perform the optimization on the source/ directory

### ISSUE THREAD

**Issue by Nowaker** [plasticine/middleman-imageoptim#22]
What do you think of an option to optimize the source images directly? Thanks to this I wouldn't have to optimize the images every time a site is generated, but only after I added new images. I would just commit the optimized files to the repo. Thanks for considering.

**Comment by plasticine** [comment]
That’s not really the way that middleman extensions work—also as of `0.2.0` there is a cache that this gem will use to make sure that it is not reprocessing images.
