### ISSUE TITLE
Unknown Extension: imageoptim

### ISSUE THREAD

**Issue by chrisboden** [plasticine/middleman-imageoptim#39]
Hi, when running Middleman server from terminal I am getting this error. I have installed both the 'middleman-imageoptim' and 'image_optim' gems and included them in the gemfile with:

gem 'image_optim'
gem 'middleman-imageoptim'

and added the default config to the config.rb file

Any thoughts on where I might be going wrong?

**Comment by katsuma** [comment]
Why don't you try `bundle exec middleman` ?

**Comment by chrisboden** [comment]
Tried that, error persists:

bash-3.2# bundle exec middleman
== The Middleman is loading
== Unknown Extension: imageoptim
== LiveReload is waiting for a browser to connect
== The Middleman is standing watch at http://0.0.0.0:4567
== Inspect your site configuration at http://0.0.0.0:4567/__middleman/

**Comment by vespertilian** [comment]
I am also seeing this error when I try to build.

**Comment by vespertilian** [comment]
Downgraded middleman fixed it. Moved to 3.3.8.

**Comment by codyrobbins** [comment]
I’m running into this issue as well. I’m using Middleman 3.3.10 with Rbenv on Ruby 2.2.1.

**Comment by codyrobbins** [comment]
After some more digging, this appears to have already been fixed in `master` by 361bdd8efc039027b0eac2e7b3a86153b55c0cdf.

**Comment by plasticine** [comment]
> After some more digging, this appears to have already been fixed in master by 361bdd8.

That’s correct—it should be, I need to release a new version.

**Comment by ketan** [comment]
>> After some more digging, this appears to have already been fixed in master by 361bdd8.

> That’s correct—it should be, I need to release a new version.

Is there something on master that is preventing a release?

**Comment by plasticine** [comment]
`0.2.1` is available now.

**Comment by ketan** [comment]
:+1:

**Comment by chrisboden** [comment]
Sorry, I'm still experiencing the issue after upgrade to 0.2.1.
From terminal:

bash-3.2# gem install 'middleman-imageoptim'
Fetching: middleman-imageoptim-0.2.1.gem (100%)
Successfully installed middleman-imageoptim-0.2.1

then

bash-3.2# middleman server
WARN: Unresolved specs during Gem::Specification.reset:
      json (>= 1.7.7, ~> 1.7)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
== The Middleman is loading
== Unknown Extension: imageoptim
