### ISSUE TITLE
Compatibility with Middleman v4

### ISSUE THREAD

**Issue by renatocarvalho** [plasticine/middleman-imageoptim#40]
Hey guys, I tried to use middleman-imageoptim with Middleman v4 but it seems that's not working yet. I know that v4 still in beta, but I was wondering if there's already a version that supports v4.

Thanks!

**Comment by plasticine** [comment]
> I know that v4 still in beta, but I was wondering if there's already a version that supports v4.

@renatocarvalho At this point there isn’t, no. I’m waiting until 4.0 is released before I spend much time on it tbh — though a PR implementing support would be most welcome.

**Comment by renatocarvalho** [comment]
@plasticine Thanks!
