### ISSUE TITLE
NoMethodError: undefined method `build_dir`

### ISSUE THREAD

**Issue by hello-jason** [plasticine/middleman-imageoptim#51]
Receiving the following error during build on Middleman v4:

```bash
NoMethodError: undefined method `build_dir' for
```

**Comment by hello-jason** [comment]
The simple fix above makes this gem work on Middleman v4 for me. Can you (@georgecheng) submit a PR so @plasticine can get that merged in?

**Comment by hwhelchel** [comment]
@hello-jason if you use master of this repo, that bug is already fixed. @plasticine has not cut a new release of the gem with this fix.

**Comment by hello-jason** [comment]
Thanks for the heads up @hwhelchel. Confirming that this is indeed fixed in master of this repo. The following line in `Gemfile` works:

```ruby
gem "middleman-imageoptim", :git => "https://github.com/plasticine/middleman-imageoptim", :branch => "master"
```

Closing this issue, but would be nice to get an updated gem release.
