### ISSUE TITLE
middleman build fails with EXIFR::JPEG

### ISSUE THREAD

**Issue by javierg** [plasticine/middleman-imageoptim#54]
This was fixed on https://github.com/toy/image_optim/pull/150, So I guess updating the dependency fixes the issue, I did an update in a fork and is working correctly now.

**Comment by sgerrand** [comment]
@javierg: Given this change was merged in a539cae, can this issue be closed?

**Comment by javierg** [comment]
@sgerrand sorry, sure

**Comment by javierg** [comment]
solved
