### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by sgerrand** [plasticine/middleman-imageoptim#56]
👋  @plasticine: Can the changes [between v0.2.6 and the current HEAD of master](https://github.com/plasticine/middleman-imageoptim/compare/v0.2.1...a539cae) be released?

**Comment by ceri-richmond** [comment]
+1

**Comment by sgerrand** [comment]
👋 @plasticine: It's been some time since I opened this issue. What are your plans for the future of this gem?

**Comment by sgerrand** [comment]
🙋 Still waiting on a response. Perhaps this gem could be taken on by a new maintainer?

**Comment by plasticine** [comment]
Done https://rubygems.org/gems/middleman-imageoptim/versions/0.3.0

**Comment by sgerrand** [comment]
Thank you! 💝

**Comment by plasticine** [comment]
@sgerrand no worries — sorry for the delay, I’m not doing much with Middleman these days! 🙃
